POST http://localhost:4002/cadastro
// definindo qual o formado do arquivo vvvvvvvv
content-type: application/json    

    {
        "nome": "Lincoln",
        "email": "lincoln@gmail.com",
        "senha": "lincolndev"
    }

### 


GET http://localhost:4002/cadastro

###


GET http://localhost:4002/cadastro/lincoln@gmail.com


###

PUT http://localhost:4002/cadastro/lincoln@gmail.com
// definindo qual o formado do arquivo vvvvvvvv
content-type: application/json    

    {
        "nome": "Lincolndev",
        "senha": "caneta1717"
    }